//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tj_blog
    {
        public long ID { get; set; }
        public string CONTENTS { get; set; }
        public string LOGGED { get; set; }
        public string LINK_TO { get; set; }
        public string CLASS { get; set; }
        public string OCCURED { get; set; }
        public string MOOD { get; set; }
        public string USERNAME { get; set; }
    }
}
