//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tj_mouse
    {
        public long id { get; set; }
        public string logged { get; set; }
        public Nullable<long> pixels_moved { get; set; }
    }
}
