//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tj_programs
    {
        public long id { get; set; }
        public string title { get; set; }
        public Nullable<long> time { get; set; }
        public Nullable<long> idle { get; set; }
        public Nullable<long> keys { get; set; }
        public string starttime { get; set; }
        public string savetime { get; set; }
    }
}
